### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by Pearadox99** [tylermorganwall/rayrollercoaster#1]
I was messing around and found this package but am unable to get it working. Using the code you have on the other page I keep getting the error below after running "generate_rayshader_coaster(light=FALSE, ambient_light=T)".

Error in rayrender::obj_model(cache_filename, x = -bbox_center[1], y = -bbox_center[2], : 
unused argument (texture = TRUE)

**Comment by tylermorganwall** [comment]
You just need to update to the latest version of rayrender on Github:

```r
remotes::install_github("tylermorganwall/rayrender")
```
